services:
  nginx:
    hostname: nginx
    image: nginx:1-alpine
    ports:
      - '8080:80'
    volumes:
      - www_dir:/var/www/html
      - ./files/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    hostname: php-fpm
    image: sepastian/omeka-s
    build: .
    volumes:
      - www_dir:/var/www/html
      - ./files/php-fpm/var/www/html/config/local.config.php:/var/www/html/config/local.config.php
    environment:
      - OMEKA_DB_CONNECTION_URL
  mariadb:
    hostname: mariadb
    image: mariadb:lts
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_HOST
      - MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD
volumes:
  www_dir:
