services:
  nginx:
    hostname: nginx
    image: nginx:1-alpine
    ports:
      - '8080:80'
    volumes:
      # Shared /var/www/html between omeka-s and nginx
      - www_dir:/var/www/html
      - ./files/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  omeka-s:
    hostname: omeka-s
    image: ghcr.io/sepastian/omeka-s-docker:latest
    build: .
    volumes:
      # Shared /var/www/html between omeka-s and nginx
      - www_dir:/var/www/html
      # Enable logging in omeka-s
      - ./files/omeka-s/var/www/html/config/local.config.php:/var/www/html/config/local.config.php
      # Max children setting in PHP-FPM
      - ./files/omeka-s/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - OMEKA_DB_CONNECTION_URL
  mariadb:
    hostname: mariadb
    image: mariadb:lts
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_HOST
      - MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD
    volumes:
      - mariadb_dir:/var/lib/mysql
      #- ./files/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
volumes:
  www_dir:
  mariadb_dir:
  