services:
  nginx:
    hostname: nginx
    image: nginx:1-alpine
    ports:
      - '8080:80'
    volumes:
      - www_dir:/var/www/html
      - ./files/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    hostname: php-fpm
    image: sepastian/omeka-s
    build: .
    volumes:
      - www_dir:/var/www/html
    environment:
      MARIADB_DATABASE: omeka
      MARIADB_USER: omeka
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_HOST: mariadb
    secrets:
      - mariadb_password
  mariadb:
    hostname: mariadb
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_DATABASE: omeka
      MARIADB_USER: omeka
    secrets:
      - mariadb_root_password
      - mariadb_password
volumes:
  www_dir:
secrets:
  mariadb_root_password:
    file: ./secrets/mariadb_root_password
  mariadb_password:
    file: ./secrets/mariadb_password
    
